"""Add memory column to chat_sessions

Revision ID: c435cee1950e
Revises: b95055a2149f
Create Date: 2025-08-06 04:51:03.059771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c435cee1950e'
down_revision: Union[str, Sequence[str], None] = 'b95055a2149f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('memory', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'memory')
    # ### end Alembic commands ###
